### ISSUE TITLE
Question about pcen_cuda_kernel

### ISSUE THREAD

**Issue by chanil1218** [daemon/pytorch-pcen#1]
Thanks you for sharing your code.
When I'm reading your code, I've noticed that [`pcen_cuda_kernel`](https://github.com/daemon/pytorch-pcen/blob/master/pcen/pcen.py#L69) is missing. 
Is that part not implemented yet or omitted?

**Comment by daemon** [comment]
Good question -- that's not implemented yet. Even though the existing code works on CUDA, the routine isn't optimized. I was planning to use cuPy and pynvrtc to implement a CUDA kernel for PCEN, similar to [the fused QRNN kernel](https://github.com/salesforce/pytorch-qrnn/tree/master/torchqrnn), but I haven't had the chance.
